### ISSUE TITLE
Blue background

### ISSUE THREAD

**Issue by pwndumb** [audibleblink/hackthebox.vim#1]
First, congratulations for nice work. 
I don't know if this is normal behavior put when I set the colorsheme to hackthebox, my background is set to blue. 

OS: Mac OS Big Sur 
Terminal: Iterm2

<img width="636" alt="Screen Shot 2021-04-11 at 3 27 19 PM" src="https://user-images.githubusercontent.com/6491534/114316543-6a2fd600-9ada-11eb-8be2-fb6275791412.png">
<img width="654" alt="Screen Shot 2021-04-11 at 3 27 48 PM" src="https://user-images.githubusercontent.com/6491534/114316556-7ae04c00-9ada-11eb-8f05-d78538a53688.png">

**Comment by audibleblink** [comment]
What I think is happening here is that your Vim is using the 3rd set of fallback colors. (16 Colors).

Could be a couple things:

1. The terminal emulator you're using should support TrueColor for this theme to work in the best configuration.
2. Vim must have `termguicolors` enabled. [more info](https://vimhelp.org/options.txt.html#%27termguicolors%27)

If you get this working, you _may_ eventually find that stuff breaks again if you fire up Vim inside of Tmux.
Here's a good troubleshooting guide and compatibility list - https://gist.github.com/XVilka/8346728

**Comment by audibleblink** [comment]
This might be a quicker answer for you. Try this in your .vimrc

```vim
  " Colorscheme
    syntax on
    if has('termguicolors')
      set termguicolors
      set t_ut=
    endif
    colorscheme hackthebox
```

**Comment by pwndumb** [comment]
> This might be a quicker answer for you. Try this in your .vimrc
> 
> ```viml
>   " Colorscheme
>     syntax on
>     if has('termguicolors')
>       set termguicolors
>       set t_ut=
>     endif
>     colorscheme hackthebox
> ```

Thanks. Problem solved. This color scheme is very beautiful !!!

![image](https://user-images.githubusercontent.com/6491534/114331920-79834380-9b1b-11eb-916a-fbff89ac15a6.png)
